site_name: GPTDiff Docs
extra:
  cname: gptdiff.255labs.xyz
site_name: GPTDiff
docs_dir: docs
site_dir: site
strict: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    scheme: slate
    primary: deep purple
    accent: blue

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI Reference: cli.md
  - gptpatch: gptpatch.md
  - API Reference: api.md
  - Core Concepts: concepts.md
  - Architecture: concepts/architecture.md
  - Examples:
      - Basic Usage: examples/basic.md
      - Advanced Refactoring: examples/advanced.md
      - Automation with While Loops: examples/automation.md
  - Development:
      - Testing Practices: development/testing.md
      - Contributing Guide: development/contributing.md
extra:
  social:
    - name: 255labs.xyz
      icon: fontawesome/solid/globe
      link: https://255labs.xyz
plugins: