site_name: GPTDiff
docs_dir: docs
site_dir: site
strict: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    scheme: slate
    primary: deep purple
    accent: blue

nav:
  - API Reference: api.md