site_name: GPTDiff
docs_dir: docs
site_dir: site
strict: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    scheme: slate
    primary: deep purple
    accent: blue

nav:
  - Home: index.md
  - CLI Reference: cli.md
  - API Reference: api.md
  - Core Concepts: concepts.md
  - Examples:
      - Basic Usage: examples/basic.md
      - Advanced Refactoring: examples/advanced.md
      - Automation with While Loops: examples/automation.md
      - Common Recipes: examples/recipes.md
  - Development:
      - Testing Guide: development/testing.md