title: GPTDiff
baseurl: /
url: "https://255labs.github.io/gptdiff"
repository: 255BITS/gptdiff
plugins:
  - jekyll-feed  

markdown: kramdown
kramdown:
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    theme: "monokai"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark