name: Deploy Documentation

on:
  push:
    branches:
      - main  # Adjust if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build site
        run: mkdocs build --site-dir public  # Ensure output is in 'public'

      - name: Ensure CNAME is set
        run: echo "gptdiff.255labs.xyz" > public/CNAME  # Correct location

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public  # This must match the correct output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

