name: documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mkdocs-material
      - run: |
          echo "gptdiff.255labs.xyz" > CNAME
          mkdocs gh-deploy --force

